/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const KButtonEmits2: typeof import('@keep-design/components/src')['KButtonEmits2']
}
